### ISSUE TITLE
Peers Dropping from Testnet

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/substrate#8]
# Describe the issue:

When attempting to run a testnet over public internet, the nodes will establish the connection with the bootstrap node and proccess with no issues. Peers show as they are added, consensus is going, and even seeing Reorgs etc. 

After some time (3+ hours) We will then see all nodes drop all peers, in the bootstrap node there are no errors when this occurs. Then each node will operate on its own version of the chain moving forward. 

# To Reproduce:

This error will not replicate on an internal network, this will need to be tested with a server and pc

Ensure docker volume has been wiped. 

Setup bootstrap node & farmer on 1 computer with the following command

**Node**

```markdown
docker network create spartan
docker volume create spartan-node-template
docker pull subspacelabs/node-template-spartan
docker run --rm --init -it \
--net spartan \
--name node-template-spartan \
--mount source=node-template-spartan,target=/var/spartan \
--publish 0.0.0.0:30333:30333 \
  --publish 127.0.0.1:9944:9944 \
  --publish 127.0.0.1:9933:9933 \
subspacelabs/node-template-spartan \
--dev \
--base-path /var/spartan \
--ws-external \
--telemetry-url 'wss://telemetry.polkadot.io/submit/ 9' \
--node-key 0000000000000000000000000000000000000000000000000000000000000001
```

**Farmer**

```markdown
#Pull and Plot
docker volume create spartan-farmer
docker pull subspacelabs/spartan-farmer
docker run --rm -it \
  --name spartan-farmer \
  --mount source=spartan-farmer,target=/var/spartan \
  subspacelabs/spartan-farmer plot 256000 spartan

#Run Farmer
docker run --rm --init -it \
  --net spartan \
  --name spartan-farmer \
  --mount source=spartan-farmer,target=/var/spartan \
  subspacelabs/spartan-farmer \
    farm \
    --ws-server ws://node-template-spartan:9944
```

Once farmer node and bootstrap node are running we will then run a full node on the second system. 

**Full Node** - Note the IP Address will need to be changed to match your bootstrap server.

```markdown
docker network create spartan
docker volume create spartan-node-template
docker pull subspacelabs/node-template-spartan
docker run --rm --init -it \
--net spartan \
--name node-template-spartan-full \
--mount source=node-template-spartan,target=/var/spartan \
subspacelabs/node-template-spartan \
--dev \
--base-path /var/spartan \
--ws-external \
--bootnodes /ip4/165.232.157.230/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp \
--telemetry-url 'wss://telemetry.polkadot.io/submit/ 9'
```

**Farmer**

```markdown
#Pull & Plot
docker volume create spartan-farmer
docker pull subspacelabs/spartan-farmer
docker run --rm -it \
  --name spartan-farmer \
  --mount source=spartan-farmer,target=/var/spartan \
  subspacelabs/spartan-farmer plot 256000 spartan

#Run Farmer
docker run --rm --init -it \
  --net spartan \
  --name spartan-farmer \
  --mount source=spartan-farmer,target=/var/spartan \
  subspacelabs/spartan-farmer \
    farm \
    --ws-server ws://node-template-spartan-full:9944
```

From here you will need to wait about 3+ hours. Around the 3 hour mark you should see all peers drop from the server. 

# Expected Behavior:

To not drop the peers. 

# Platform and Versions:

Ubuntu LTS 20.04 Kernel 5.4.0 - Digital Ocean Server (Bootstrap Node)

Ubuntu LTS 20.04 Kernel 5.13.4 - Laptop (Full Node)

Docker and Docker Images all up to date on both.

**Comment by nazar-pc** [comment]
It did drop for me too, will dig as to why it happened, but it takes some time to happen, may be related to epoch/era/eon transition.

**Comment by nazar-pc** [comment]
I belive the root cause for this is the same as for #9 and is caused by some error in salt update mechanism:
```
2021-08-11 01:39:52  💔 Verification failed for block 0xe59d03168d5411937464cd1bdd523b92847c4bf95bbad907a7ca8dce4fb5dac4 received from peer: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, "Invalid commitment for salt for slot 1628645992"    
2021-08-11 01:39:56  💤 Idle (0 peers), best: #3656 (0x3ec2…6167), finalized #0 (0x469f…6cda), ⬇ 3.6kiB/s ⬆ 97 B/s    
2021-08-11 01:39:58  💔 Verification failed for block 0xe59d03168d5411937464cd1bdd523b92847c4bf95bbad907a7ca8dce4fb5dac4 received from peer: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, "Invalid commitment for salt for slot 1628645992"    
```

Will have to make salt update more frequent and see if I can reproduce it.

**Comment by nazar-pc** [comment]
The root of the issue is found, I think I also have a solution, will put it together tomorrow
